# Generated by Django 2.2.14 on 2020-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_domain', models.CharField(max_length=256)),
                ('redirect_url', models.URLField(max_length=2048)),
                ('redirect_params', models.CharField(blank=True, max_length=2048, null=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=256, null=True)),
                ('referrer_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('browser', models.CharField(blank=True, max_length=64, null=True)),
                ('os', models.CharField(blank=True, max_length=64, null=True)),
                ('platform', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'redirect_data',
            },
        ),
    ]
